import 'package:lifeclient/product/model/memory_model.dart';

final class MemoryEmptyModel {
  const MemoryEmptyModel._();

  static MemoryModel empty = MemoryModel(documentId: '');

  static List<MemoryModel> mockMemories = [
    MemoryModel(
      documentId: 'memory_1',
      title: 'Güzel Bir Günbatımı',
      description: 'Deniz kenarında çektiğimiz bu muhteşem günbatımı anısı.',
      imageUrl: 'https://picsum.photos/400/400?random=1',
      thumbnailUrl: 'https://picsum.photos/200/200?random=1',
      userId: 'user_1',
      tags: const ['günbatımı', 'deniz', 'doğa'],
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    MemoryModel(
      documentId: 'memory_2',
      title: 'Arkadaşlarla Piknik',
      description: 'Harika geçen piknik gününden kareler.',
      imageUrl: 'https://picsum.photos/400/400?random=2',
      thumbnailUrl: 'https://picsum.photos/200/200?random=2',
      userId: 'user_1',
      tags: const ['piknik', 'arkadaşlar', 'eğlence'],
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    MemoryModel(
      documentId: 'memory_3',
      title: 'Şehir Manzarası',
      description: 'Gece şehrin ışıltılı manzarası.',
      imageUrl: 'https://picsum.photos/400/400?random=3',
      thumbnailUrl: 'https://picsum.photos/200/200?random=3',
      userId: 'user_1',
      tags: const ['şehir', 'gece', 'manzara'],
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    MemoryModel(
      documentId: 'memory_4',
      title: 'Lezzetli Yemek',
      description: 'Bugün yaptığımız nefis pasta.',
      imageUrl: 'https://picsum.photos/400/400?random=4',
      thumbnailUrl: 'https://picsum.photos/200/200?random=4',
      userId: 'user_1',
      tags: const ['yemek', 'pasta', 'mutfak'],
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
      updatedAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
    MemoryModel(
      documentId: 'memory_5',
      title: 'Doğa Yürüyüşü',
      description: 'Ormandaki muhteşem doğa yürüyüşümüz.',
      imageUrl: 'https://picsum.photos/400/400?random=5',
      thumbnailUrl: 'https://picsum.photos/200/200?random=5',
      userId: 'user_1',
      tags: const ['doğa', 'yürüyüş', 'orman'],
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    MemoryModel(
      documentId: 'memory_6',
      title: 'Kedi Dostumuz',
      description: 'Sokak kedisi dostumuzla güzel anlar.',
      imageUrl: 'https://picsum.photos/400/400?random=6',
      thumbnailUrl: 'https://picsum.photos/200/200?random=6',
      userId: 'user_1',
      tags: const ['kedi', 'hayvan', 'dostluk'],
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      updatedAt: DateTime.now().subtract(const Duration(days: 6)),
    ),
    MemoryModel(
      documentId: 'memory_7',
      title: 'Kahve Molası',
      description: 'Sabah kahvesi ile güne başlangıç.',
      imageUrl: 'https://picsum.photos/400/400?random=7',
      thumbnailUrl: 'https://picsum.photos/200/200?random=7',
      userId: 'user_1',
      tags: const ['kahve', 'sabah', 'mola'],
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      updatedAt: DateTime.now().subtract(const Duration(days: 7)),
    ),
    MemoryModel(
      documentId: 'memory_8',
      title: 'Kitap Okuma Zamanı',
      description: 'Huzurlu bir kitap okuma seansı.',
      imageUrl: 'https://picsum.photos/400/400?random=8',
      thumbnailUrl: 'https://picsum.photos/200/200?random=8',
      userId: 'user_1',
      tags: const ['kitap', 'okuma', 'huzur'],
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 8)),
    ),
    MemoryModel(
      documentId: 'memory_9',
      title: 'Müzik Keyfi',
      description: 'Gitar çalarken çektiğimiz bu anı.',
      imageUrl: 'https://picsum.photos/400/400?random=9',
      thumbnailUrl: 'https://picsum.photos/200/200?random=9',
      userId: 'user_1',
      tags: const ['müzik', 'gitar', 'sanat'],
      createdAt: DateTime.now().subtract(const Duration(days: 9)),
      updatedAt: DateTime.now().subtract(const Duration(days: 9)),
    ),
  ];
}
