// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:lifeclient/product/feature/cache/hive_v2/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppCacheModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(GeoPointAdapter());
    registerAdapter(MemoryCacheModelAdapter());
    registerAdapter(MemoryModelAdapter());
    registerAdapter(StoreModelAdapter());
    registerAdapter(StoreModelCacheAdapter());
    registerAdapter(UserApplicationModelAdapter());
    registerAdapter(UserApplicationStatusAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserRoleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppCacheModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(GeoPointAdapter());
    registerAdapter(MemoryCacheModelAdapter());
    registerAdapter(MemoryModelAdapter());
    registerAdapter(StoreModelAdapter());
    registerAdapter(StoreModelCacheAdapter());
    registerAdapter(UserApplicationModelAdapter());
    registerAdapter(UserApplicationStatusAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserRoleAdapter());
  }
}
