// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUOAiKOMpuNxnpysbMoN9gx85LSRNc--I',
    appId: '1:128619632572:android:deb8dc72bddd03c8c6bdb9',
    messagingSenderId: '128619632572',
    projectId: 'savehatay',
    databaseURL: 'https://savehatay-default-rtdb.firebaseio.com',
    storageBucket: 'savehatay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0ND6I8WABYRgWmoqkSgHKV9dZ_r1FOE',
    appId: '1:128619632572:ios:38588d72e15e331cc6bdb9',
    messagingSenderId: '128619632572',
    projectId: 'savehatay',
    databaseURL: 'https://savehatay-default-rtdb.firebaseio.com',
    storageBucket: 'savehatay.appspot.com',
    androidClientId:
        '128619632572-50nc245ghr0emi8dadr8a5leril7dodi.apps.googleusercontent.com',
    iosClientId:
        '128619632572-rc594ocdb393i2000je814298sqr623d.apps.googleusercontent.com',
    iosBundleId: 'com.hatayiyasat.app',
  );
}
